[project]
name = "finance-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "chainlit>=2.5.5",
    "langchain-mcp-adapters>=0.1.7",
    "langchain[google-genai]>=0.3.26",
    "langgraph>=0.5.0",
    "mcp>=1.10.1",
    "pandas>=2.3.0",
    "ta-lib>=0.6.4",
    "tabulate>=0.9.0",
    "yfinance>=0.2.64",
]
